function entities/properties/index
function entities/events/index
function players/manager
function rendering/manager
function animations/tick
function sounds/manager
function particles/manager
function dialogue/manager
function debug/index